FROM node:lts-alpine as build
WORKDIR /app
COPY ./.. ./..
RUN npm ci

RUN npm run build:test


FROM nginx:stable-alpine AS runtime
COPY --from=build /../app/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

ENTRYPOINT ["nginx-debug", "-g", "daemon off;"]